export const MAX_TEXT_LENGTH = 10
export const MAX_TODO_LENGTH = 5
export const TODO_ERROR = {
    DEFAULT: "",
    EMPTY_VALUE: "EMPTY_VALUE",
    EXCEEDED_MAX_TEXT_LENGTH: "EXCEEDED_MAX_TEXT_LENGTH",
    EXCEEDED_MAX_TODO_LENGTH: "EXCEEDED_MAX_TODO_LENGTH",
    DUPLICATE_TODO: "DUPLICATE_TODO"
}
